# eksmc.py -- Enhanced Keyed ShiftMerge Cipher (EKSMC)
# Usage: import encrypt, decrypt from this module, or run as script to see an example.
# Author: generated by ChatGPT for Thea (student project)
import os, json, base64, hashlib
from math import log2
from typing import List, Tuple

def to_b64(b: bytes) -> str:
    return base64.b64encode(b).decode('ascii')

def from_b64(s: str) -> bytes:
    return base64.b64decode(s.encode('ascii'))

def make_keystream(key: bytes, nonce: bytes, length: int) -> bytes:
    out = bytearray()
    counter = 0
    while len(out) < length:
        ctr_bytes = counter.to_bytes(4, 'big')
        block = hashlib.sha256(key + nonce + ctr_bytes).digest()
        out.extend(block)
        counter += 1
    return bytes(out[:length])

def derive_key(passphrase: str = None, salt: bytes = None, iterations: int = 200000) -> Tuple[bytes, bytes]:
    if passphrase is None:
        salt = salt or os.urandom(16)
        key = os.urandom(16)
    else:
        salt = salt or os.urandom(16)
        key = hashlib.pbkdf2_hmac('sha256', passphrase.encode('utf-8'), salt, iterations, dklen=16)
    return key, salt

def alphashift_char(ch: str, shift: int) -> str:
    if 'A' <= ch <= 'Z':
        base = ord('A')
        val = ord(ch) - base
        new = (val + shift) % 26
        return chr(base + new)
    elif 'a' <= ch <= 'z':
        base = ord('a')
        val = ord(ch) - base
        new = (val + shift) % 26
        return chr(base + new)
    else:
        return ch

def alphashift_char_reverse(ch: str, shift: int) -> str:
    if 'A' <= ch <= 'Z':
        base = ord('A')
        val = ord(ch) - base
        new = (val - shift) % 26
        return chr(base + new)
    elif 'a' <= ch <= 'z':
        base = ord('a')
        val = ord(ch) - base
        new = (val - shift) % 26
        return chr(base + new)
    else:
        return ch

def byte_shift_char(ch: str, shift_byte: int) -> str:
    code = ord(ch)
    new_code = (code + shift_byte) % 0x110000
    return chr(new_code)

def byte_shift_char_reverse(ch: str, shift_byte: int) -> str:
    code = ord(ch)
    new_code = (code - shift_byte) % 0x110000
    return chr(new_code)

def shiftmerge_transpose(chars: List[str], key_bytes: bytes) -> List[str]:
    if not chars:
        return []
    odd = chars[0::2]
    even = chars[1::2]
    if len(even) == 0:
        return odd[:]
    shift_amount = key_bytes[1] % len(even) if len(even) > 0 else 0
    shift_amount = int(shift_amount)
    even_shifted = even[-shift_amount:] + even[:-shift_amount] if shift_amount != 0 else even[:]
    merged = []
    for i in range(max(len(odd), len(even_shifted))):
        if i < len(odd):
            merged.append(odd[i])
        if i < len(even_shifted):
            merged.append(even_shifted[i])
    return merged

def shiftmerge_untranspose(merged: List[str], key_bytes: bytes) -> List[str]:
    if not merged:
        return []
    total = len(merged)
    odd_len = (total + 1) // 2
    even_len = total // 2
    odd = merged[0::2][:odd_len]
    even = merged[1::2][:even_len]
    if even_len == 0:
        return odd[:]
    shift_amount = key_bytes[1] % even_len if even_len > 0 else 0
    shift_amount = int(shift_amount)
    even_unshifted = even[shift_amount:] + even[:shift_amount] if shift_amount != 0 else even[:]
    out = []
    for i in range(max(len(odd), len(even_unshifted))):
        if i < len(odd):
            out.append(odd[i])
        if i < len(even_unshifted):
            out.append(even_unshifted[i])
    return out

def serialize_space_positions(positions: List[int]) -> bytes:
    if not positions:
        return b''
    s = ','.join(str(p) for p in positions)
    return s.encode('ascii')

def deserialize_space_positions(b: bytes) -> List[int]:
    if not b:
        return []
    s = b.decode('ascii')
    return [int(x) for x in s.split(',') if x != '']

def encrypt_blob(blob: bytes, key: bytes, nonce: bytes, label: bytes) -> bytes:
    ks = make_keystream(key, nonce + label, len(blob))
    return bytes(a ^ b for a, b in zip(blob, ks))

def decrypt_blob(enc: bytes, key: bytes, nonce: bytes, label: bytes) -> bytes:
    ks = make_keystream(key, nonce + label, len(enc))
    return bytes(a ^ b for a, b in zip(enc, ks))

def encrypt(plaintext: str, passphrase: str = None, noise_len: int = 3) -> str:
    key, salt = derive_key(passphrase)
    space_positions = []
    compact_chars = []
    flags = []
    for ch in plaintext:
        if ch == ' ':
            space_positions.append(len(compact_chars))
        else:
            compact_chars.append(ch)
            flags.append(1 if ('A' <= ch <= 'Z' or 'a' <= ch <= 'z') else 0)
    substituted = []
    kb = key
    for i, ch in enumerate(compact_chars):
        kb_val = kb[i % len(kb)]
        if flags[i] == 1:
            shift = kb_val % 26
            substituted.append(alphashift_char(ch, shift))
        else:
            substituted.append(byte_shift_char(ch, kb_val))
    transposed_list = shiftmerge_transpose(substituted, kb)
    main_cipher_str = ''.join(transposed_list)
    main_cipher_bytes = main_cipher_str.encode('utf-8')
    space_bytes = serialize_space_positions(space_positions)
    flags_bytes = bytes(flags)
    nonce = os.urandom(12)
    enc_space = encrypt_blob(space_bytes, key, nonce, b'space')
    enc_flags = encrypt_blob(flags_bytes, key, nonce, b'flags')
    noiseL = os.urandom(noise_len)
    noiseR = os.urandom(noise_len)
    package = {
        'salt': to_b64(salt),
        'nonce': to_b64(nonce),
        'main_cipher': to_b64(main_cipher_bytes),
        'noiseL': to_b64(noiseL),
        'space_enc': to_b64(enc_space),
        'flags_enc': to_b64(enc_flags),
        'noiseR': to_b64(noiseR)
    }
    return json.dumps(package)

def decrypt(package_json: str, passphrase: str = None) -> str:
    pkg = json.loads(package_json)
    salt = from_b64(pkg['salt'])
    nonce = from_b64(pkg['nonce'])
    main_cipher_bytes = from_b64(pkg['main_cipher'])
    enc_space = from_b64(pkg['space_enc'])
    enc_flags = from_b64(pkg['flags_enc'])
    key, _ = derive_key(passphrase, salt=salt)
    space_bytes = decrypt_blob(enc_space, key, nonce, b'space')
    space_positions = deserialize_space_positions(space_bytes)
    flags_bytes = decrypt_blob(enc_flags, key, nonce, b'flags')
    flags = list(flags_bytes)
    main_cipher_str = main_cipher_bytes.decode('utf-8')
    transposed_chars = list(main_cipher_str)
    untransposed = shiftmerge_untranspose(transposed_chars, key)
    recovered = []
    kb = key
    for i, ch in enumerate(untransposed):
        kb_val = kb[i % len(kb)]
        is_alpha = flags[i] == 1
        if is_alpha:
            shift = kb_val % 26
            recovered.append(alphashift_char_reverse(ch, shift))
        else:
            recovered.append(byte_shift_char_reverse(ch, kb_val))
    out = []
    rec_len = len(recovered)
    pos_set = set(space_positions)
    for i in range(rec_len + 1):
        if i in pos_set:
            out.append(' ')
        if i < rec_len:
            out.append(recovered[i])
    return ''.join(out)

def shannon_entropy(data: bytes) -> float:
    if not data:
        return 0.0
    counts = {}
    for b in data:
        counts[b] = counts.get(b, 0) + 1
    total = len(data)
    ent = 0.0
    for v in counts.values():
        p = v / total
        ent -= p * (log2(p) if p > 0 else 0.0)
    return ent

def brute_force_time_days(key_bits: int, rate_per_sec: float = 1e13) -> float:
    avg_seconds = (2 ** (key_bits - 1)) / rate_per_sec
    return avg_seconds / 86400.0

if __name__ == '__main__':
    sample_plain = "John.Doe_24@example.com My pass is Secret123!"
    passphrase = "MyStrongPassphrase123!"
    print("Plaintext:", sample_plain)
    pkg = encrypt(sample_plain, passphrase=passphrase, noise_len=4)
    print("\\nPackage JSON:", pkg)
    recovered = decrypt(pkg, passphrase=passphrase)
    print("\\nRecovered plaintext:", recovered)
    pkgobj = json.loads(pkg)
    main_b = from_b64(pkgobj['main_cipher'])
    print("\\nEntropy of main ciphertext bytes:", shannon_entropy(main_b))
    print("Avg crack time for 128-bit key at 1e13 tries/sec (days):", brute_force_time_days(128, 1e13))